version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: cinema_db
    environment:
      POSTGRES_DB: "cinema_app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - cinemadb-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema_app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4:7.2
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "pin11kelinkirill@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "kelinkirill"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db

  backend:
    image: cinema_image
    container_name: fastapi_backend
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:80"
    networks:
      - db
    command: bash start.sh

volumes:
  cinemadb-data:
  pgadmin-data:

networks:
  db:
    driver: bridge
