"""change fields in table films

Revision ID: 7cb6e0b09805
Revises: 009346249b8e
Create Date: 2024-01-17 03:08:08.201449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb6e0b09805"
down_revision: Union[str, None] = "009346249b8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("film", sa.Column("title", sa.String(), nullable=False))
    op.add_column("film", sa.Column("director", sa.String(), nullable=False))
    op.add_column("film", sa.Column("is_in_cinemas", sa.Boolean(), nullable=False))
    op.drop_column("film", "directors")
    op.drop_column("film", "in_cinemas")
    op.drop_column("film", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "film", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "film",
        sa.Column("in_cinemas", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "film", sa.Column("directors", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("film", "is_in_cinemas")
    op.drop_column("film", "director")
    op.drop_column("film", "title")
    # ### end Alembic commands ###
